<a href="https://colab.research.google.com/github/haliberry29/SadiyaTijjaniBaba_MachineLearning/blob/main/AI_Powered_Agribusiness_Pricing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

| Column Name                     | Description                                                                      |
| ------------------------------- | -------------------------------------------------------------------------------- |
| `farm_id`                       | Unique identifier for each farm operation or agricultural site                   |
| `region`                        | Geographic region where the farm is located                                      |
| `crop_type`                     | Type of crop being cultivated (e.g., corn, soybean, wheat)                       |
| `soil_moisture_%`               | Soil water content percentage indicating moisture availability                   |
| `soil_pH`                       | Soil acidity/alkalinity measurement affecting crop growth                        |
| `temperature_C`                 | Average environmental temperature in Celsius                                     |
| `rainfall_mm`                   | Total rainfall amount in millimeters                                             |
| `humidity_%`                    | Atmospheric humidity percentage                                                  |
| `sunlight_hours`                | Number of sunlight exposure hours received                                       |
| `irrigation_type`               | Irrigation method used (drip, sprinkler, flood, etc.)                            |
| `fertilizer_type`               | Type of fertilizer applied to crops                                              |
| `pesticide_usage_ml`            | Amount of pesticide applied in milliliters                                       |
| `sowing_date`                   | Date when crops were planted                                                     |
| `harvest_date`                  | Date when crops were harvested                                                   |
| `total_days`                    | Total crop growth duration between sowing and harvest                            |
| `yield_kg_per_hectare`          | Crop production yield per hectare                                                |
| `sensor_id`                     | Identifier for IoT or agricultural monitoring sensor                             |
| `timestamp`                     | Date-time record of observation or sensor reading                                |
| `latitude`                      | Geographic latitude coordinate of the farm                                       |
| `longitude`                     | Geographic longitude coordinate of the farm                                      |
| `NDVI_index`                    | Normalized Difference Vegetation Index measuring crop health from remote sensing |
| `crop_disease_status`           | Indicates whether crops are healthy or affected by disease                       |
| `product_price`                 | Selling price of agricultural product or input                                   |
| `quantity_sold`                 | Number of units sold                                                             |
| `revenue`                       | Total revenue generated from sales                                               |
| `discount_pct`                  | Discount percentage applied during sale                                          |
| `corn_futures_price`            | Market futures price for corn commodity                                          |
| `soybean_futures_price`         | Market futures price for soybean commodity                                       |
| `fertilizer_market_index`       | Market index representing fertilizer price trends                                |
| `diesel_price`                  | Diesel fuel price impacting machinery and logistics costs                        |
| `inflation_rate`                | General inflation percentage affecting operational costs                         |
| `competitor_price`              | Estimated competitor pricing for similar products                                |
| `customer_segment`              | Classification of customer type (small farm, enterprise, cooperative, etc.)      |
| `farm_size_hectares`            | Total farm operational area in hectares                                          |
| `purchase_frequency`            | Number of purchases made within a defined period                                 |
| `customer_lifetime_value`       | Estimated long-term customer revenue value                                       |
| `demand_index`                  | Relative measure of market demand intensity                                      |
| `regional_market_share_pct`     | Estimated percentage of regional market controlled                               |
| `week`                          | Week number extracted from timestamp                                             |
| `quarter`                       | Fiscal quarter extracted from timestamp                                          |
| `season`                        | Agricultural season classification (Spring, Summer, Fall, Winter)                |
| `holiday_flag`                  | Binary indicator identifying holiday periods                                     |
| `drought_index`                 | Numerical indicator of drought severity                                          |
| `heat_stress_index`             | Crop heat stress severity indicator                                              |
| `flood_risk_score`              | Estimated flood vulnerability score                                              |
| `soil_health_score`             | Composite soil quality and fertility score                                       |
| `crop_disease_risk`             | Estimated probability/risk category of crop disease occurrence                   |
| `water_availability_index`      | Relative water resource availability indicator                                   |
| `inventory_level`               | Available inventory stock quantity                                               |
| `supplier_risk_score`           | Supplier reliability and supply chain risk indicator                             |
| `logistics_cost`                | Transportation and delivery cost estimate                                        |
| `lead_time_days`                | Estimated delivery or replenishment lead time                                    |
| `unit_cost`                     | Estimated operational or production cost per unit                                |
| `profit_margin`                 | Profit percentage after subtracting costs from price                             |
| `pricing_recommendation`        | AI-generated pricing action recommendation                                       |
| `pricing_recommendation_reason` | Explanation supporting the pricing recommendation                                |
| `hormuz_scenario`               | Simulated geopolitical disruption scenario related to Strait of Hormuz           |
| `oil_price_shock_multiplier`    | Multiplier representing oil price shock severity                                 |
| `adjusted_diesel_price`         | Diesel price adjusted for geopolitical disruptions                               |
| `adjusted_fertilizer_index`     | Fertilizer price index adjusted for energy market shocks                         |
| `adjusted_logistics_cost`       | Logistics cost adjusted for fuel and supply chain disruption                     |
| `supply_chain_disruption_score` | Composite indicator of supply chain instability                                  |
| `farm_input_inflation_pct`      | Estimated inflation percentage in agricultural input costs                       |
| `adjusted_unit_cost`            | Production cost adjusted for geopolitical and inflationary pressure              |
| `revenue_risk_score`            | Estimated financial risk exposure to revenue                                     |
| `margin_compression_pct`        | Percentage reduction in profit margin due to rising costs                        |
| `adjusted_profit_margin`        | Profit margin after geopolitical and inflation adjustments                       |
| `revenue_at_risk`               | Estimated revenue potentially lost under disruption scenarios                    |
| `geopolitical_pricing_strategy` | Recommended pricing strategy under geopolitical conditions                       |
| `geopolitical_business_summary` | AI-generated business interpretation of geopolitical risk conditions             |

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/Smart_Farming_Crop_Yield_2024.csv')

In [ ]:
df.columns

Index(['farm_id', 'region', 'crop_type', 'soil_moisture_%', 'soil_pH',
       'temperature_C', 'rainfall_mm', 'humidity_%', 'sunlight_hours',
       'irrigation_type', 'fertilizer_type', 'pesticide_usage_ml',
       'sowing_date', 'harvest_date', 'total_days', 'yield_kg_per_hectare',
       'sensor_id', 'timestamp', 'latitude', 'longitude', 'NDVI_index',
       'crop_disease_status'],
      dtype='object')

In [ ]:
df.head(5)

,farm_id,region,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,sowing_date,harvest_date,total_days,yield_kg_per_hectare,sensor_id,timestamp,latitude,longitude,NDVI_index,crop_disease_status
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,1/8/2024,5/9/2024,122,4408.07,SENS0001,3/19/2024,14.970941,82.997689,0.63,Mild
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,2/4/2024,5/26/2024,112,5389.98,SENS0002,4/21/2024,16.613022,70.869009,0.58,NaN
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,2/3/2024,6/26/2024,144,2931.16,SENS0003,2/28/2024,19.503156,79.068206,0.80,Mild
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,2/21/2024,7/4/2024,134,4227.80,SENS0004,5/14/2024,31.071298,85.519998,0.44,NaN
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,2/5/2024,5/20/2024,105,4979.96,SENS0005,4/13/2024,16.568540,81.691720,0.84,Severe

In [ ]:
df.isnull().sum()

farm_id                   0
region                    0
crop_type                 0
soil_moisture_%           0
soil_pH                   0
temperature_C             0
rainfall_mm               0
humidity_%                0
sunlight_hours            0
irrigation_type         150
fertilizer_type           0
pesticide_usage_ml        0
sowing_date               0
harvest_date              0
total_days                0
yield_kg_per_hectare      0
sensor_id                 0
timestamp                 0
latitude                  0
longitude                 0
NDVI_index                0
crop_disease_status     130
dtype: int64

In [ ]:
df["product_price"] = np.random.normal(420, 40, len(df))

df["quantity_sold"] = (
    df["yield_kg_per_hectare"] * np.random.uniform(0.8, 1.3, len(df))
).astype(int)

df["revenue"] = df["product_price"] * df["quantity_sold"]

df["discount_pct"] = np.random.uniform(0, 0.15, len(df))

In [ ]:
df.head(5)

,farm_id,region,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,sensor_id,timestamp,latitude,longitude,NDVI_index,crop_disease_status,product_price,quantity_sold,revenue,discount_pct
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,SENS0001,3/19/2024,14.970941,82.997689,0.63,Mild,441.931674,4581,2.024489e+06,0.149062
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,SENS0002,4/21/2024,16.613022,70.869009,0.58,NaN,392.567828,6707,2.632952e+06,0.042628
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,SENS0003,2/28/2024,19.503156,79.068206,0.80,Mild,395.141076,3786,1.496004e+06,0.048842
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,SENS0004,5/14/2024,31.071298,85.519998,0.44,NaN,498.480245,3719,1.853848e+06,0.061032
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,SENS0005,4/13/2024,16.568540,81.691720,0.84,Severe,421.311871,6424,2.706507e+06,0.036854

In [ ]:
import numpy as np
import pandas as pd

# -----------------------------
# RANDOM SEED FOR REPRODUCIBILITY
# -----------------------------
np.random.seed(42)

# Assume your dataframe already exists
# df = pd.read_csv("your_dataset.csv")

# -----------------------------
# MARKET & ECONOMIC FEATURES
# -----------------------------

# Corn futures price ($/bushel)
df["corn_futures_price"] = np.random.normal(6.2, 0.7, len(df)).round(2)

# Soybean futures price ($/bushel)
df["soybean_futures_price"] = np.random.normal(13.5, 1.2, len(df)).round(2)

# Fertilizer market index
df["fertilizer_market_index"] = np.random.normal(110, 15, len(df)).round(2)

# Diesel price ($/gallon)
df["diesel_price"] = np.random.normal(4.1, 0.4, len(df)).round(2)

# Inflation rate (%)
df["inflation_rate"] = np.random.uniform(2.0, 8.0, len(df)).round(2)

# Competitor product price
df["competitor_price"] = (
    df["product_price"] * np.random.uniform(0.9, 1.1, len(df))
).round(2)

# -----------------------------
# CUSTOMER & DEMAND FEATURES
# -----------------------------

# Customer segment
customer_segments = ["Small Farm", "Commercial", "Enterprise", "Cooperative"]

df["customer_segment"] = np.random.choice(
    customer_segments,
    len(df)
)

# Farm size (hectares)
df["farm_size_hectares"] = np.random.randint(10, 5000, len(df))

# Purchase frequency per year
df["purchase_frequency"] = np.random.randint(1, 15, len(df))

# Customer lifetime value ($)
df["customer_lifetime_value"] = np.random.normal(
    25000,
    8000,
    len(df)
).round(2)

# Demand index
df["demand_index"] = np.random.uniform(0.5, 1.5, len(df)).round(2)

# Regional market share (%)
df["regional_market_share_pct"] = np.random.uniform(
    1,
    35,
    len(df)
).round(2)

# -----------------------------
# TEMPORAL FEATURES
# -----------------------------

# Convert dates to datetime
df["sowing_date"] = pd.to_datetime(df["sowing_date"])
df["harvest_date"] = pd.to_datetime(df["harvest_date"])
df['timestamp'] = pd.to_datetime(df['timestamp'])
# Extract week
df["week"] = df["timestamp"].dt.isocalendar().week

# Extract quarter
df["quarter"] = df["timestamp"].dt.quarter

# Season mapping
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

df["season"] = df["timestamp"].dt.month.apply(get_season)

# Holiday flag
df["holiday_flag"] = np.random.choice(
    [0, 1],
    len(df),
    p=[0.9, 0.1]
)

# -----------------------------
# ENVIRONMENTAL RISK FEATURES
# -----------------------------

# Drought index
df["drought_index"] = np.random.uniform(0, 5, len(df)).round(2)

# Heat stress index
df["heat_stress_index"] = (
    (df["temperature_C"] / 40) * 100
).round(2)

# Flood risk score
df["flood_risk_score"] = np.random.uniform(
    0,
    100,
    len(df)
).round(2)

# Soil health score
df["soil_health_score"] = np.random.uniform(
    50,
    100,
    len(df)
).round(2)

# Crop disease risk
disease_risk = ["Low", "Moderate", "High"]

df["crop_disease_risk"] = np.random.choice(
    disease_risk,
    len(df),
    p=[0.6, 0.3, 0.1]
)

# Water availability index
df["water_availability_index"] = np.random.uniform(
    0,
    1,
    len(df)
).round(2)

# -----------------------------
# INVENTORY & SUPPLY CHAIN
# -----------------------------

# Inventory level
df["inventory_level"] = np.random.randint(
    100,
    5000,
    len(df)
)

# Supplier risk score
df["supplier_risk_score"] = np.random.uniform(
    0,
    100,
    len(df)
).round(2)

# Logistics cost ($)
df["logistics_cost"] = np.random.normal(
    500,
    120,
    len(df)
).round(2)

# Lead time (days)
df["lead_time_days"] = np.random.randint(
    1,
    30,
    len(df)
)

# -----------------------------
# PROFITABILITY FEATURES
# -----------------------------

# Unit production cost
df["unit_cost"] = (
    df["product_price"] * np.random.uniform(0.5, 0.85, len(df))
).round(2)

# Profit margin
df["profit_margin"] = (
    (df["product_price"] - df["unit_cost"])
    / df["product_price"]
    * 100
).round(2)

# -----------------------------
# AI PRICING RECOMMENDATION
# -----------------------------

def pricing_recommendation(row):

    if row["drought_index"] > 3 and row["demand_index"] > 1.1:
        return "Increase price by 5%"

    elif row["inventory_level"] > 4000:
        return "Offer 10% discount"

    elif row["competitor_price"] < row["product_price"]:
        return "Reduce price by 3%"

    else:
        return "Maintain current pricing"

df["pricing_recommendation"] = df.apply(
    pricing_recommendation,
    axis=1
)

# -----------------------------
# AI BUSINESS EXPLANATION
# -----------------------------

def recommendation_reason(row):

    if row["drought_index"] > 3:
        return "High drought risk increasing regional demand pressure."

    elif row["inventory_level"] > 4000:
        return "Excess inventory detected."

    elif row["competitor_price"] < row["product_price"]:
        return "Competitor pricing pressure identified."

    else:
        return "Market conditions stable."

df["pricing_recommendation_reason"] = df.apply(
    recommendation_reason,
    axis=1
)

# -----------------------------
# PREVIEW DATASET
# -----------------------------

print(df.head())

# -----------------------------
# SAVE ENHANCED DATASET
# -----------------------------

df.to_csv(
    "enhanced_agribusiness_pricing_dataset.csv",
    index=False
)

print("Enhanced dataset saved successfully.")

    farm_id       region crop_type  soil_moisture_%  soil_pH  temperature_C  \
0  FARM0001  North India     Wheat            35.95     5.99          17.79
1  FARM0002    South USA   Soybean            19.74     7.24          30.18
2  FARM0003    South USA     Wheat            29.32     7.16          27.37
3  FARM0004  Central USA     Maize            17.33     6.03          33.73
4  FARM0005  Central USA    Cotton            19.37     5.92          33.86

   rainfall_mm  humidity_%  sunlight_hours irrigation_type  ...  \
0        75.62       77.03            7.27             NaN  ...
1        89.91       61.13            5.67       Sprinkler  ...
2       265.43       68.87            8.23            Drip  ...
3       212.01       70.46            5.03       Sprinkler  ...
4       269.09       55.73            7.93             NaN  ...

  crop_disease_risk  water_availability_index inventory_level  \
0               Low                      0.14             476
1               Low                      0.78            1072
2          Moderate                      0.80            4313
3               Low                      0.54            3176
4               Low                      0.31             543

  supplier_risk_score  logistics_cost  lead_time_days unit_cost profit_margin  \
0               69.82          504.81               7    363.76         17.69
1               62.38          248.98              28    306.89         21.82
2               18.90          455.70               5    229.39         41.95
3               46.94          471.16              15    293.90         41.04
4               72.03          410.12              20    215.38         48.88

   pricing_recommendation                      pricing_recommendation_reason
0      Reduce price by 3%            Competitor pricing pressure identified.
1      Reduce price by 3%  High drought risk increasing regional demand p...
2      Offer 10% discount                         Excess inventory detected.
3      Reduce price by 3%            Competitor pricing pressure identified.
4      Reduce price by 3%            Competitor pricing pressure identified.

[5 rows x 56 columns]
Enhanced dataset saved successfully.

In [ ]:
import numpy as np
import pandas as pd

# -----------------------------
# RANDOM SEED FOR REPRODUCIBILITY
# -----------------------------
np.random.seed(42)

# Assume your dataframe already exists
# df = pd.read_csv("your_dataset.csv")

# -----------------------------
# MARKET & ECONOMIC FEATURES
# -----------------------------

# Corn futures price ($/bushel)
df["corn_futures_price"] = np.random.normal(6.2, 0.7, len(df)).round(2)

# Soybean futures price ($/bushel)
df["soybean_futures_price"] = np.random.normal(13.5, 1.2, len(df)).round(2)

# Fertilizer market index
df["fertilizer_market_index"] = np.random.normal(110, 15, len(df)).round(2)

# Diesel price ($/gallon)
df["diesel_price"] = np.random.normal(4.1, 0.4, len(df)).round(2)

# Inflation rate (%)
df["inflation_rate"] = np.random.uniform(2.0, 8.0, len(df)).round(2)

# Competitor product price
df["competitor_price"] = (
    df["product_price"] * np.random.uniform(0.9, 1.1, len(df))
).round(2)

# -----------------------------
# CUSTOMER & DEMAND FEATURES
# -----------------------------

# Customer segment
customer_segments = ["Small Farm", "Commercial", "Enterprise", "Cooperative"]

df["customer_segment"] = np.random.choice(
    customer_segments,
    len(df)
)

# Farm size (hectares)
df["farm_size_hectares"] = np.random.randint(10, 5000, len(df))

# Purchase frequency per year
df["purchase_frequency"] = np.random.randint(1, 15, len(df))

# Customer lifetime value ($)
df["customer_lifetime_value"] = np.random.normal(
    25000,
    8000,
    len(df)
).round(2)

# Demand index
df["demand_index"] = np.random.uniform(0.5, 1.5, len(df)).round(2)

# Regional market share (%)
df["regional_market_share_pct"] = np.random.uniform(
    1,
    35,
    len(df)
).round(2)

# -----------------------------
# TEMPORAL FEATURES
# -----------------------------

# Convert dates to datetime
df["sowing_date"] = pd.to_datetime(df["sowing_date"])
df["harvest_date"] = pd.to_datetime(df["harvest_date"])

# Extract week
df["week"] = df["timestamp"].dt.isocalendar().week

# Extract quarter
df["quarter"] = df["timestamp"].dt.quarter

# Season mapping
def get_season(month):
    if month in [12, 1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Spring"
    elif month in [6, 7, 8]:
        return "Summer"
    else:
        return "Fall"

df["season"] = df["timestamp"].dt.month.apply(get_season)

# Holiday flag
df["holiday_flag"] = np.random.choice(
    [0, 1],
    len(df),
    p=[0.9, 0.1]
)

# -----------------------------
# ENVIRONMENTAL RISK FEATURES
# -----------------------------

# Drought index
df["drought_index"] = np.random.uniform(0, 5, len(df)).round(2)

# Heat stress index
df["heat_stress_index"] = (
    (df["temperature_C"] / 40) * 100
).round(2)

# Flood risk score
df["flood_risk_score"] = np.random.uniform(
    0,
    100,
    len(df)
).round(2)

# Soil health score
df["soil_health_score"] = np.random.uniform(
    50,
    100,
    len(df)
).round(2)

# Crop disease risk
disease_risk = ["Low", "Moderate", "High"]

df["crop_disease_risk"] = np.random.choice(
    disease_risk,
    len(df),
    p=[0.6, 0.3, 0.1]
)

# Water availability index
df["water_availability_index"] = np.random.uniform(
    0,
    1,
    len(df)
).round(2)

# -----------------------------
# INVENTORY & SUPPLY CHAIN
# -----------------------------

# Inventory level
df["inventory_level"] = np.random.randint(
    100,
    5000,
    len(df)
)

# Supplier risk score
df["supplier_risk_score"] = np.random.uniform(
    0,
    100,
    len(df)
).round(2)

# Logistics cost ($)
df["logistics_cost"] = np.random.normal(
    500,
    120,
    len(df)
).round(2)

# Lead time (days)
df["lead_time_days"] = np.random.randint(
    1,
    30,
    len(df)
)

# -----------------------------
# PROFITABILITY FEATURES
# -----------------------------

# Unit production cost
df["unit_cost"] = (
    df["product_price"] * np.random.uniform(0.5, 0.85, len(df))
).round(2)

# Profit margin
df["profit_margin"] = (
    (df["product_price"] - df["unit_cost"])
    / df["product_price"]
    * 100
).round(2)

# -----------------------------
# AI PRICING RECOMMENDATION
# -----------------------------

def pricing_recommendation(row):

    if row["drought_index"] > 3 and row["demand_index"] > 1.1:
        return "Increase price by 5%"

    elif row["inventory_level"] > 4000:
        return "Offer 10% discount"

    elif row["competitor_price"] < row["product_price"]:
        return "Reduce price by 3%"

    else:
        return "Maintain current pricing"

df["pricing_recommendation"] = df.apply(
    pricing_recommendation,
    axis=1
)

# -----------------------------
# AI BUSINESS EXPLANATION
# -----------------------------

def recommendation_reason(row):

    if row["drought_index"] > 3:
        return "High drought risk increasing regional demand pressure."

    elif row["inventory_level"] > 4000:
        return "Excess inventory detected."

    elif row["competitor_price"] < row["product_price"]:
        return "Competitor pricing pressure identified."

    else:
        return "Market conditions stable."

df["pricing_recommendation_reason"] = df.apply(
    recommendation_reason,
    axis=1
)

# -----------------------------
# PREVIEW DATASET
# -----------------------------

print(df.head())

# -----------------------------
# SAVE ENHANCED DATASET
# -----------------------------

df.to_csv(
    "enhanced_agribusiness_pricing_dataset.csv",
    index=False
)

print("Enhanced dataset saved successfully.")

    farm_id       region crop_type  soil_moisture_%  soil_pH  temperature_C  \
0  FARM0001  North India     Wheat            35.95     5.99          17.79
1  FARM0002    South USA   Soybean            19.74     7.24          30.18
2  FARM0003    South USA     Wheat            29.32     7.16          27.37
3  FARM0004  Central USA     Maize            17.33     6.03          33.73
4  FARM0005  Central USA    Cotton            19.37     5.92          33.86

   rainfall_mm  humidity_%  sunlight_hours irrigation_type  ...  \
0        75.62       77.03            7.27             NaN  ...
1        89.91       61.13            5.67       Sprinkler  ...
2       265.43       68.87            8.23            Drip  ...
3       212.01       70.46            5.03       Sprinkler  ...
4       269.09       55.73            7.93             NaN  ...

  crop_disease_risk  water_availability_index inventory_level  \
0               Low                      0.14             476
1               Low                      0.78            1072
2          Moderate                      0.80            4313
3               Low                      0.54            3176
4               Low                      0.31             543

  supplier_risk_score  logistics_cost  lead_time_days unit_cost profit_margin  \
0               69.82          504.81               7    363.76         17.69
1               62.38          248.98              28    306.89         21.82
2               18.90          455.70               5    229.39         41.95
3               46.94          471.16              15    293.90         41.04
4               72.03          410.12              20    215.38         48.88

   pricing_recommendation                      pricing_recommendation_reason
0      Reduce price by 3%            Competitor pricing pressure identified.
1      Reduce price by 3%  High drought risk increasing regional demand p...
2      Offer 10% discount                         Excess inventory detected.
3      Reduce price by 3%            Competitor pricing pressure identified.
4      Reduce price by 3%            Competitor pricing pressure identified.

[5 rows x 56 columns]
Enhanced dataset saved successfully.

In [ ]:
df.head(5)

,farm_id,region,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,crop_disease_risk,water_availability_index,inventory_level,supplier_risk_score,logistics_cost,lead_time_days,unit_cost,profit_margin,pricing_recommendation,pricing_recommendation_reason
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,Low,0.14,476,69.82,504.81,7,363.76,17.69,Reduce price by 3%,Competitor pricing pressure identified.
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,Low,0.78,1072,62.38,248.98,28,306.89,21.82,Reduce price by 3%,High drought risk increasing regional demand p...
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,Moderate,0.80,4313,18.90,455.70,5,229.39,41.95,Offer 10% discount,Excess inventory detected.
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,Low,0.54,3176,46.94,471.16,15,293.90,41.04,Reduce price by 3%,Competitor pricing pressure identified.
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,Low,0.31,543,72.03,410.12,20,215.38,48.88,Reduce price by 3%,Competitor pricing pressure identified.

In [ ]:
df.crop_type.unique()

array(['Wheat', 'Soybean', 'Maize', 'Cotton', 'Rice'], dtype=object)

In [ ]:
df.region.unique()

array(['North India', 'South USA', 'Central USA', 'East Africa',
       'South India'], dtype=object)

In [ ]:
df.to_csv("AI_Smart_Agribusiness.csv")

In [ ]:
hormuz_scenarios = [
    "normal",
    "moderate_disruption",
    "severe_disruption",
    "closure"
]

df["hormuz_scenario"] = np.random.choice(
    hormuz_scenarios,
    len(df),
    p=[0.65, 0.20, 0.10, 0.05]
)

In [ ]:
def oil_shock_multiplier(scenario):

    if scenario == "normal":
        return np.random.uniform(0.98, 1.03)

    elif scenario == "moderate_disruption":
        return np.random.uniform(1.08, 1.18)

    elif scenario == "severe_disruption":
        return np.random.uniform(1.20, 1.40)

    else:
        return np.random.uniform(1.45, 1.80)

df["oil_price_shock_multiplier"] = df[
    "hormuz_scenario"
].apply(oil_shock_multiplier)

In [ ]:
df["adjusted_diesel_price"] = (
    df["diesel_price"]
    * df["oil_price_shock_multiplier"]
).round(2)

In [ ]:
df["adjusted_fertilizer_index"] = (
    df["fertilizer_market_index"]
    * (
        1
        + (
            (df["oil_price_shock_multiplier"] - 1)
            * 0.75
        )
    )
).round(2)

In [ ]:
df["adjusted_logistics_cost"] = (
    df["logistics_cost"]
    * (
        1
        + (
            (df["oil_price_shock_multiplier"] - 1)
            * 0.60
        )
    )
).round(2)

In [ ]:
df["farm_input_inflation_pct"] = (
    (
        (
            df["adjusted_fertilizer_index"]
            - df["fertilizer_market_index"]
        )
        / df["fertilizer_market_index"]
    )
    * 100
).round(2)

In [ ]:
df["revenue_at_risk"] = (
    df["revenue"]
    * (
        df["farm_input_inflation_pct"] / 100
    )
).round(2)

In [ ]:
# ---------------------------------------------------------
# Adjusted unit production cost after geopolitical shock
# ---------------------------------------------------------

df["adjusted_unit_cost"] = (
    df["unit_cost"]
    * (
        1
        + (
            df["farm_input_inflation_pct"] / 100
        )
        * 0.55
    )
).round(2)

In [ ]:
df["margin_compression_pct"] = (
    (
        (
            df["adjusted_unit_cost"]
            - df["unit_cost"]
        )
        / df["unit_cost"]
    )
    * 100
).round(2)

In [ ]:
# ---------------------------------------------------------
# Margin compression percentage
# ---------------------------------------------------------

df["margin_compression_pct"] = (
    (
        (
            df["adjusted_unit_cost"]
            - df["unit_cost"]
        )
        / df["unit_cost"]
    )
    * 100
).round(2)

In [ ]:
def geopolitical_strategy(row):

    if row["hormuz_scenario"] == "closure":
        return "Increase prices aggressively"

    elif row["farm_input_inflation_pct"] > 15:
        return "Adjust pricing to protect margins"

    elif row["inventory_level"] > 4000:
        return "Offer targeted discounts"

    else:
        return "Maintain current pricing"

df["geopolitical_pricing_strategy"] = df.apply(
    geopolitical_strategy,
    axis=1
)

In [ ]:
def geopolitical_summary(row):

    if row["hormuz_scenario"] == "closure":

        return (
            "Severe geopolitical disruption detected. "
            "Fuel and fertilizer costs are rising sharply."
        )

    elif row["farm_input_inflation_pct"] > 10:

        return (
            "Input cost inflation increasing operational risk."
        )

    else:

        return (
            "Market conditions remain stable."
        )

df["geopolitical_summary"] = df.apply(
    geopolitical_summary,
    axis=1
)

In [ ]:
df

,farm_id,region,crop_type,soil_moisture_%,soil_pH,temperature_C,rainfall_mm,humidity_%,sunlight_hours,irrigation_type,...,oil_price_shock_multiplier,adjusted_diesel_price,adjusted_fertilizer_index,adjusted_logistics_cost,farm_input_inflation_pct,revenue_at_risk,adjusted_unit_cost,margin_compression_pct,geopolitical_pricing_strategy,geopolitical_summary
0,FARM0001,North India,Wheat,35.95,5.99,17.79,75.62,77.03,7.27,NaN,...,0.996176,4.39,130.61,503.65,-0.29,-5871.02,363.18,-0.16,Maintain current pricing,Market conditions remain stable.
1,FARM0002,South USA,Soybean,19.74,7.24,30.18,89.91,61.13,5.67,Sprinkler,...,1.165665,4.52,139.26,273.73,12.42,327012.69,327.85,6.83,Maintain current pricing,Input cost inflation increasing operational risk.
2,FARM0003,South USA,Wheat,29.32,7.16,27.37,265.43,68.87,8.23,Drip,...,1.009681,3.81,111.70,458.35,0.73,10920.83,230.31,0.40,Offer targeted discounts,Market conditions remain stable.
3,FARM0004,Central USA,Maize,17.33,6.03,33.73,212.01,70.46,5.03,Sprinkler,...,1.005900,4.12,100.74,472.83,0.44,8156.93,294.61,0.24,Maintain current pricing,Market conditions remain stable.
4,FARM0005,Central USA,Cotton,19.37,5.92,33.86,269.09,55.73,7.93,NaN,...,1.017169,4.10,122.02,414.34,1.29,34913.95,216.91,0.71,Maintain current pricing,Market conditions remain stable.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,FARM0496,Central USA,Rice,42.85,6.70,30.85,52.35,79.58,7.25,Manual,...,1.026784,4.65,142.90,626.14,2.01,32531.11,257.48,1.11,Maintain current pricing,Market conditions remain stable.
496,FARM0497,North India,Soybean,34.22,6.75,17.46,256.23,45.14,5.78,NaN,...,1.013284,4.14,142.32,557.60,0.99,12831.71,272.25,0.54,Maintain current pricing,Market conditions remain stable.
497,FARM0498,North India,Cotton,15.93,5.72,17.03,288.96,57.87,7.69,Drip,...,0.993255,3.72,127.48,519.74,-0.51,-5262.82,304.68,-0.28,Maintain current pricing,Market conditions remain stable.
498,FARM0499,Central USA,Soybean,38.61,6.20,17.08,279.06,73.09,9.60,Drip,...,1.137056,4.58,138.25,583.88,10.28,127546.90,265.33,5.65,Offer targeted discounts,Input cost inflation increasing operational risk.
499,FARM0500,North India,Wheat,30.22,7.42,20.57,72.61,89.74,5.09,NaN,...,1.002116,3.81,119.08,538.18,0.16,3839.09,324.96,0.09,Offer targeted discounts,Market conditions remain stable.